### ISSUE TITLE
RuntimeError: Entry symbol not found | optix.init() not working

### ISSUE THREAD

**Issue by brugalada** [keithroe/PyOptiX#5]
Hi,

So, trying to run the basic checks, but I cannot get pass this error. Basically, I'm just trying to initialise the OptiX module with:
`import optix;
optix.init()`

This returns:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Entry symbol not found`

I tried to trace back the origin of the error but it is either a problem with the installation of PyOptiX (but I don't know why) or then I have to trace it all the way back to the files in the OptiX SDK. In particular, _optix_stubs.h_ This is out of my expertise however.

I run out of ideas... Any suggestion on how to fix it?

**Comment by gmarkall** [comment]
Is that the full traceback? Can you explain a bit more about how you built PyOptiX, and what versions of Python / the tools you have?

**Comment by brugalada** [comment]
Yes, what I've written is all I get from the terminal. 

The installation process was a bit messy so I will try to summarise it:
1. conda create -n pyoptix python numpy conda-forge::cupy pybind11 pillow cmake numba (_also adding other packages that I like, e.g. Jupyter and such_)
2. Build PyOptix: no problems
3. Realize that the function `compile_cuda` of the module cuda.compiler does not accept _nvvm_options_ in the Conda version of Numba
4. Use conda to install llvmlite 0.37.0.dev0 (required by the latest github version of numba)
5. Use conda to uninstall numba
6. Build numba from source

I will try it again but creating a new environment and doing things properly. Maybe I should have built PyOptix last...

**Comment by brugalada** [comment]
I re-started from scratch with a new conda environment and did the following:
1. Install basic python: conda create -n python3_numba python=3.9 numpy scipy matplotlib jupyter pandas astropy
2. Install -c anaconda gxx_linux-64 gcc_linux-64
3. conda install -c numba/label/dev llvmlite
4. Install conda-forge::cupy pybind11 pillow cmake cudatoolkit=10.2
5. Build Numba
6. export PYOPTIX_CMAKE_ARGS="-DOptiX_INSTALL_DIR=XXX"
7. Build PyOptix with pip3 install --global-option build --global-option --debug .

Now cupy is properly installed (which I think was the issue before), and so is Numba. PyOptix builds without issue as well.

But when I run hello.py I get this:
`Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "cupy/cuda/stream.pyx", line 345, in cupy.cuda.stream.Stream.__del__
AttributeError: 'Stream' object has no attribute 'ptr'
Traceback (most recent call last):
  File "/home/pramos/github/PyOptiX/examples/hello.py", line 67, in <module>
    def array_to_device_memory( numpy_array, stream=cp.cuda.Stream() ):
  File "cupy/cuda/stream.pyx", line 338, in cupy.cuda.stream.Stream.__init__
  File "cupy_backends/cuda/api/runtime.pyx", line 853, in cupy_backends.cuda.api.runtime.streamCreate
  File "cupy_backends/cuda/api/runtime.pyx", line 261, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInsufficientDriver: CUDA driver version is insufficient for CUDA runtime version`

Based on the (little) research I have done on this error, I believe the problem now is on the drivers installed at the machine (or, alternatively, the mode -Performance or Power Saving Mode-). I will try to sort it out...

**Comment by gmarkall** [comment]
What is the output of `numba -s`?

**Comment by brugalada** [comment]
`System info:
--------------------------------------------------------------------------------
__Time Stamp__
Report started (local time)                   : 2021-05-28 11:28:46.750255
UTC start time                                : 2021-05-28 09:28:46.750263
Running time (s)                              : 1.528846

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : cascadelake
CPU Count                                     : 44
Number of accessible CPUs                     : 32
List of accessible CPUs cores                 : 0-447
CFS Restrictions (CPUs worth of runtime)      : None

CPU Features                                  : 64bit adx aes avx avx2 avx512bw
                                                avx512cd avx512dq avx512f avx512vl
                                                avx512vnni bmi bmi2 clflushopt
                                                clwb cmov cx16 cx8 f16c fma
                                                fsgsbase fxsr invpcid lzcnt mmx
                                                movbe pclmul pku popcnt prfchw
                                                rdrnd rdseed rtm sahf sse sse2
                                                sse3 sse4.1 sse4.2 ssse3 xsave
                                                xsavec xsaveopt xsaves

Memory Total (MB)                             : 95087
Memory Available (MB)                         : 45446

__OS Information__
Platform Name                                 : Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with-glibc2.17
Platform Release                              : 3.10.0-957.27.2.el7.x86_64
OS Name                                       : Linux
OS Version                                    : #1 SMP Mon Jul 29 17:46:05 UTC 2019
OS Specific Version                           : ?
Libc Version                                  : glibc 2.17

__Python Information__
Python Compiler                               : GCC 7.3.0
Python Implementation                         : CPython
Python Version                                : 3.9.5
Python Locale                                 : None.UTF-8

__Numba Toolchain Versions__
Numba Version                                 : 0.54.0.dev0+558.ge314821-py3.9-linux-x86_64.egg
llvmlite Version                              : 0.37.0dev0+23.g990a0d4

__LLVM Information__
LLVM Version                                  : 10.0.1

__CUDA Information__
CUDA Device Initialized                       : True
CUDA Driver Version                           : 10010
CUDA Runtime Version                          : ?
CUDA Detect Output:
Found 4 CUDA devices
id 0    b'GeForce RTX 2080 Ti'                              [SUPPORTED]
                      Compute Capability: 7.5
                           PCI Device ID: 0
                              PCI Bus ID: 61
                                Watchdog: Disabled
             FP32/FP64 Performance Ratio: 32
id 1    b'GeForce RTX 2080 Ti'                              [SUPPORTED]
                      Compute Capability: 7.5
                           PCI Device ID: 0
                              PCI Bus ID: 96
                                Watchdog: Disabled
             FP32/FP64 Performance Ratio: 32
id 2    b'GeForce RTX 2080 Ti'                              [SUPPORTED]
                      Compute Capability: 7.5
                           PCI Device ID: 0
                              PCI Bus ID: 177
                                Watchdog: Disabled
             FP32/FP64 Performance Ratio: 32
id 3    b'GeForce RTX 2080 Ti'                              [SUPPORTED]
                      Compute Capability: 7.5
                           PCI Device ID: 0
                              PCI Bus ID: 218
                                Watchdog: Disabled
             FP32/FP64 Performance Ratio: 32
Summary:
	4/4 devices are supported

CUDA Libraries Test Output:
None

__ROC information__
ROC Available                                 : False
ROC Toolchains                                : None
HSA Agents Count                              : 0
HSA Agents:
None
HSA Discrete GPUs Count                       : 0
HSA Discrete GPUs                             : None

__SVML Information__
SVML State, config.USING_SVML                 : False
SVML Library Loaded                           : False
llvmlite Using SVML Patched LLVM              : True
SVML Operational                              : False

__Threading Layer Information__
TBB Threading Layer Available                 : False
+--> Disabled due to Unknown import problem.
OpenMP Threading Layer Available              : True
+-->Vendor: GNU
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.

__Numba Environment Variable Information__
None found.

__Conda Information__
Conda Build                                   : not installed
Conda Env                                     : 4.10.1
Conda Platform                                : linux-64
Conda Python Version                          : 3.9.1.final.0
Conda Root Writable                           : True

__Installed Packages__
_libgcc_mutex             0.1                        main  
argon2-cffi               20.1.0           py39h27cfd23_1  
astropy                   4.2.1            py39h6323ea4_1  
async_generator           1.10               pyhd3eb1b0_0  
attrs                     21.2.0             pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
binutils_impl_linux-64    2.31.1               h6176602_1    anaconda
binutils_linux-64         2.31.1               h6176602_9    anaconda
blas                      1.0                         mkl  
bleach                    3.3.0              pyhd3eb1b0_0  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.4.13            h06a4308_1  
certifi                   2020.12.5        py39h06a4308_0  
cffi                      1.14.5           py39h261ae71_0  
cmake                     3.19.6               h973ab73_0  
cudatoolkit               10.2.89              hfd86e86_1  
cupy                      9.0.0            py39hb309dcf_1    conda-forge
cycler                    0.10.0           py39h06a4308_0  
dbus                      1.13.18              hb2f20db_0  
decorator                 5.0.9              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
entrypoints               0.3              py39h06a4308_0  
expat                     2.4.1                h2531618_2  
fastrlock                 0.6              py39h2531618_0  
fontconfig                2.13.1               h6c09931_0  
freetype                  2.10.4               h5ab3b9f_0  
gcc_impl_linux-64         7.3.0                habb00fd_1    anaconda
gcc_linux-64              7.3.0                h553295d_9    anaconda
glib                      2.68.2               h36276a3_0  
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
gxx_impl_linux-64         7.3.0                hdf63c60_1    anaconda
gxx_linux-64              7.3.0                h553295d_9    anaconda
icu                       58.2                 he6710b0_3  
importlib-metadata        3.10.0           py39h06a4308_0  
importlib_metadata        3.10.0               hd3eb1b0_0  
intel-openmp              2021.2.0           h06a4308_610  
ipykernel                 5.3.4            py39hb070fc8_0  
ipython                   7.22.0           py39hb070fc8_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.3              pyhd3eb1b0_1  
jedi                      0.17.2           py39h06a4308_1  
jinja2                    3.0.0              pyhd3eb1b0_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0            py39h06a4308_7  
jupyter_client            6.1.12             pyhd3eb1b0_0  
jupyter_console           6.4.0              pyhd3eb1b0_0  
jupyter_core              4.7.1            py39h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
kiwisolver                1.3.1            py39h2531618_0  
krb5                      1.18.2               h173b8e3_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libcurl                   7.71.1               h20c2e04_1  
libedit                   3.1.20210216         h27cfd23_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   1.0.3                h1bed415_2  
libuv                     1.40.0               h7b6447c_0  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
llvmlite                  0.37.0dev0      py39hf484d3e_23    numba/label/dev
lz4-c                     1.9.3                h2531618_0  
markupsafe                2.0.1            py39h27cfd23_0  
matplotlib                3.3.4            py39h06a4308_0  
matplotlib-base           3.3.4            py39h62a2d02_0  
mistune                   0.8.4           py39h27cfd23_1000  
mkl                       2021.2.0           h06a4308_296  
mkl-service               2.3.0            py39h27cfd23_1  
mkl_fft                   1.3.0            py39h42c9631_2  
mkl_random                1.2.1            py39ha9443f7_2  
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.0.7            py39h06a4308_0  
nbformat                  5.1.3              pyhd3eb1b0_0  
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
notebook                  6.4.0            py39h06a4308_0  
numba                     0.54.0.dev0+558.ge314821          pypi_0    pypi
numpy                     1.20.2           py39h2d18471_0  
numpy-base                1.20.2           py39hfae3a4d_0  
olefile                   0.46                       py_0  
openssl                   1.1.1k               h27cfd23_0  
optix                     0.0.1                    pypi_0    pypi
packaging                 20.9               pyhd3eb1b0_0  
pandas                    1.2.4            py39h2531618_0  
pandoc                    2.12                 h06a4308_0  
pandocfilters             1.4.3            py39h06a4308_1  
parso                     0.7.0                      py_0  
pcre                      8.44                 he6710b0_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.2.0            py39he98fc37_0  
pip                       21.1.1           py39h06a4308_0  
prometheus_client         0.10.1             pyhd3eb1b0_0  
prompt-toolkit            3.0.17             pyh06a4308_0  
prompt_toolkit            3.0.17               hd3eb1b0_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pybind11                  2.6.2            py39hff7bd54_1  
pycparser                 2.20                       py_2  
pyerfa                    2.0.0            py39h27cfd23_0  
pygments                  2.9.0              pyhd3eb1b0_0  
pynvrtc                   9.2                      pypi_0    pypi
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py39h2531618_6  
pyrsistent                0.17.3           py39h27cfd23_0  
python                    3.9.5                hdb3f193_3  
python-dateutil           2.8.1              pyhd3eb1b0_0  
python_abi                3.9                      1_cp39    conda-forge
pytz                      2021.1             pyhd3eb1b0_0  
pyzmq                     20.0.0           py39h2531618_1  
qt                        5.9.7                h5867ecd_1  
qtconsole                 5.0.3              pyhd3eb1b0_0  
qtpy                      1.9.0                      py_0  
readline                  8.1                  h27cfd23_0  
rhash                     1.4.1                h3c74f83_1  
scipy                     1.6.2            py39had2a1c9_1  
send2trash                1.5.0              pyhd3eb1b0_1  
setuptools                52.0.0           py39h06a4308_0  
sip                       4.19.13          py39h2531618_0  
six                       1.15.0           py39h06a4308_0  
sqlite                    3.35.4               hdfb4753_0  
terminado                 0.9.4            py39h06a4308_0  
testpath                  0.4.4              pyhd3eb1b0_0  
tk                        8.6.10               hbc83047_0  
tornado                   6.1              py39h27cfd23_0  
traitlets                 5.0.5              pyhd3eb1b0_0  
tzdata                    2020f                h52ac0ba_0  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1            py39h06a4308_1  
wheel                     0.36.2             pyhd3eb1b0_0  
widgetsnbextension        3.5.1            py39h06a4308_0  
xz                        5.2.5                h7b6447c_0  
zeromq                    4.3.4                h2531618_0  
zipp                      3.4.1              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0  

No errors reported.


__Warning log__
Warning (cuda): Probing CUDA failed (device and driver present, runtime problem?)
(cuda) <class 'numba.cuda.cudadrv.runtime.CudaRuntimeAPIError'>: [35] Call to cudaRuntimeGetVersion results in cudaErrorUnknown
Warning (roc): Error initialising ROC: No ROC toolchains found.
Warning (roc): No HSA Agents found, encountered exception when searching: Error at driver init: 
NUMBA_HSA_DRIVER /opt/rocm/lib/libhsa-runtime64.so is not a valid file path.  Note it must be a filepath of the .so/.dll/.dylib or the driver:
Warning (psutil): psutil cannot be imported. For more accuracy, consider installing it.
--------------------------------------------------------------------------------
If requested, please copy and paste the information between
the dashed (----) lines, or from a given specific section as
appropriate.

=============================================================
IMPORTANT: Please ensure that you are happy with sharing the
contents of the information present, any information that you
wish to keep private you should remove before sharing.
=============================================================
`

**Comment by gmarkall** [comment]
You have the 10.1 driver and the 10.2 toolkit, so the driver version is insufficient for the toolkit version. However, I think you might need the R465 (CUDA 11.3) driver for OptiX (perhaps @keithroe can confirm).

**Comment by keithroe** [comment]
Yes, optix 7.3 does require a 465+ driver.  Please note that this repository is a work-in-progress and not all functionality is fully  implemented.  I have changes in flight that will fill in all of the missing functionality and they should be merged soon.

**Comment by brugalada** [comment]
After the update of the drivers, hello.py is working! I got the intended output. I will now close the issue, thank you.
